//! Building the generated tree without touching the user's source.
//!
//! `.cargo-hole/` holds one generated `.rs` per source file that had holes, and
//! nothing else. It is *not* a crate: there is no `Cargo.toml`, and a file with
//! no holes has no artifact at all. So `cargo build` run inside the store can
//! never work, and building the generated code has to start from the real crate
//! and overlay the artifacts onto a copy of it.
//!
//! That copy is the **shadow tree**, and copying it is the whole point: the
//! generated code can be compiled, run and tested without a single byte of the
//! user's crate being rewritten. The alternative -- patching the real files and
//! restoring them afterwards, which is what the compile gate does -- is only a
//! safe trade for a check that takes seconds under a lock. A build can run for
//! minutes, can be interrupted, and can leave behind a binary the user then
//! runs; leaving the source patched for that long is a worse bet than paying for
//! a copy.
//!
//! # Why the shadow is kept
//!
//! The copy is skipped when the destination already has identical bytes. That
//! is not just an optimisation: leaving an unchanged file's mtime alone is what
//! lets cargo's incremental cache survive between runs. A shadow that was
//! rewritten wholesale every time would recompile the crate from scratch on
//! every invocation, which for a large crate is the difference between a build
//! that is usable and one that is not.

use std::path::{Path, PathBuf};
use std::process::ExitStatus;

use anyhow::{Context, Result, bail};

use crate::hole::Hole;
use crate::prober::ProberOptions;
use crate::storage::{PATCH_DIR, STORE_DIR};

/// Name of the shadow tree inside the store directory.
pub const SHADOW_DIR_NAME: &str = "build";

/// Entries never copied into the shadow tree, matched at any depth.
///
/// `target` and `node_modules` are build output and dependencies: large, and
/// regenerated by the build itself. `.git` is large and irrelevant to
/// compiling. `STORE_DIR` is the store we are overlaying *from*, and copying it
/// into the shadow would recurse into the shadow.
///
/// Everything else is copied, including other dot-entries. That is deliberate:
/// `.cargo/config.toml` changes how cargo behaves, so skipping it could make the
/// shadow build differ from a real build -- and a build command that quietly
/// builds something other than the user's crate is worse than a slow one.
const SKIP_ANY_DEPTH: &[&str] = &[STORE_DIR, "target", "node_modules", ".git"];

/// A crude guard against symlink cycles, as in [`crate::util`].
const MAX_DEPTH: usize = 32;

/// What one `sync` did, for reporting and for tests.
#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub struct SyncStats {
    /// Files written into the shadow tree.
    pub copied: usize,
    /// Files whose contents already matched, and were left untouched.
    pub reused: usize,
    /// Generated artifacts overlaid on top of the copied source.
    pub artifacts: usize,
    /// Of those, how many were overlaid as symlinks into the patch tree rather
    /// than copied.
    ///
    /// A linked artifact is one mutable file reachable by two names, so editing
    /// it in the build tree -- which is where rustc's error messages point --
    /// edits the generated code itself, and the edit survives the next build
    /// instead of being silently reverted by the overlay.
    pub linked: usize,
    /// Holes that are still `todo!()` in the tree that will be built.
    ///
    /// Not a failure: an unelaborated hole compiles, because `todo!()` has type
    /// `!`. But it does mean the build proves less than the user may think, so
    /// it is worth saying out loud.
    pub holes_left: usize,
}

impl SyncStats {
    /// Whether any artifact was overlaid at all.
    pub fn overlaid_anything(&self) -> bool {
        self.artifacts > 0
    }
}

/// A build tree that mirrors the crate with generated artifacts laid over it.
#[derive(Debug, Clone)]
pub struct Shadow {
    /// The crate root whose source is mirrored. Never written to.
    root: PathBuf,
    /// Where the mirror lives.
    dir: PathBuf,
}

impl Shadow {
    /// Place a shadow for `root`.
    ///
    /// Defaults to `<root>/.cargo-hole/build`, which keeps the tree beside the
    /// artifacts it overlays, on the same filesystem, and out of the way of the
    /// source walk (which skips dot-directories).
    pub fn new(root: impl Into<PathBuf>, build_dir: Option<PathBuf>) -> Result<Shadow> {
        let root = root.into();
        let dir = build_dir.unwrap_or_else(|| root.join(STORE_DIR).join(SHADOW_DIR_NAME));

        // Checked on *resolved* paths, because the guard exists to stop `clean`
        // deleting the user's source and a raw comparison is easy to slip past:
        // `--build-dir ..` is not recognised as an ancestor of an absolute root,
        // and `remove_dir_all("..")` would take the whole checkout.
        Shadow::guard(&root, &dir)?;

        Ok(Shadow { root, dir })
    }

    /// Refuse a shadow that would make `clean` destructive.
    ///
    /// Called both when the shadow is built and again immediately before
    /// deleting, because the tree may have been created after the first check and
    /// the resolved form is what `remove_dir_all` acts on.
    fn guard(root: &Path, dir: &Path) -> Result<()> {
        // `absolute` rather than `canonicalize`: the directory may not exist yet
        // at construction time, and canonicalizing would then fail. This only
        // has to resolve `.` and `..` for the comparison to be meaningful.
        let root = absolute(root)?;
        let dir = absolute(dir)?;

        if dir == root {
            bail!(
                "the shadow tree cannot be the crate root itself ({}); pass a different \
                 --build-dir",
                root.display()
            );
        }
        if root.starts_with(&dir) {
            bail!(
                "the shadow tree ({}) contains the crate root ({}), so cleaning it would delete \
                 the source; pass a different --build-dir",
                dir.display(),
                root.display()
            );
        }
        Ok(())
    }

    /// The crate root being mirrored.
    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Where the mirror lives.
    pub fn dir(&self) -> &Path {
        &self.dir
    }

    /// Delete the shadow tree, forcing the next build to start from scratch.
    ///
    /// This is what `--clean` does. A stale shadow is not a correctness risk --
    /// `sync` overwrites anything whose bytes differ -- but a `target/` that has
    /// drifted can produce confusing incremental artifacts, so having a way to
    /// throw it away matters.
    pub fn clean(&self) -> Result<()> {
        if !self.dir.exists() {
            return Ok(());
        }
        // Re-checked here, on the resolved path, right before the delete. The
        // first check ran against a path that may since have been created, and
        // the whole point of this function's guard is that getting it wrong
        // destroys the user's work.
        Shadow::guard(&self.root, &self.dir)?;
        std::fs::remove_dir_all(&self.dir)
            .with_context(|| format!("cannot remove {}", self.dir.display()))?;
        Ok(())
    }

    /// Mirror the crate into the shadow tree and overlay every artifact.
    ///
    /// Idempotent, and cheap on a second run: unchanged files are not rewritten,
    /// so their mtimes survive and cargo's incremental cache still applies.
    pub fn sync(&self) -> Result<SyncStats> {
        std::fs::create_dir_all(&self.dir)
            .with_context(|| format!("cannot create {}", self.dir.display()))?;

        // Now that the directory exists, resolve it fully -- through symlinks as
        // well as `..` -- so that the shadow is recognised wherever it is met,
        // including from a walk that reached it by another route.
        let resolved = std::fs::canonicalize(&self.dir)
            .with_context(|| format!("cannot resolve {}", self.dir.display()))?;
        Shadow::guard(&self.root, &resolved)?;

        let mut stats = SyncStats::default();

        // The artifacts are collected first, because their destinations are
        // files the source must *not* also be copied to. Copying both would write
        // the original `todo!()` and then immediately overwrite it, so every
        // filled file would change twice on every run and never keep its mtime --
        // exactly what the reuse check exists to avoid.
        let artifacts = self.artifacts(&resolved)?;
        let overlaid: std::collections::HashSet<PathBuf> =
            artifacts.iter().map(|(rel, _)| rel.clone()).collect();

        copy_tree(
            &self.root,
            &self.dir,
            Path::new(""),
            0,
            &resolved,
            &overlaid,
            &mut stats,
        )?;

        for (rel, artifact) in &artifacts {
            overlay(artifact, &self.dir.join(rel), &mut stats)?;
        }
        stats.artifacts = artifacts.len();

        stats.holes_left = Hole::list_holes(&self.dir).map(|h| h.len()).unwrap_or(0);
        Ok(stats)
    }

    /// Every generated artifact, as `(path relative to the crate root, path on disk)`.
    ///
    /// The patch tree mirrors the source layout (`src/lib.rs` -> `patch/src/lib.rs`),
    /// so stripping the patch prefix yields exactly the path the file must take in
    /// the build tree.
    ///
    /// `shadow_abs` is the resolved shadow tree, which must be skipped: the
    /// default shadow lives *inside* the store, so a walk that did not skip it
    /// would find its own output and overlay that, nesting a copy of the build
    /// tree deeper on every run.
    fn artifacts(&self, shadow_abs: &Path) -> Result<Vec<(PathBuf, PathBuf)>> {
        let patch = self.root.join(STORE_DIR).join(PATCH_DIR);
        if !patch.is_dir() {
            self.refuse_stale_artifacts()?;
            return Ok(Vec::new());
        }
        // Resolved, so that comparing an entry against `shadow_abs` compares
        // resolved paths to resolved paths. Without this a `--build-dir` reached
        // through a symlink or a relative path would not match, and the walk
        // would descend into the shadow tree.
        let patch = std::fs::canonicalize(&patch)
            .with_context(|| format!("cannot resolve {}", patch.display()))?;

        let mut found = Vec::new();
        collect_artifacts(&patch, shadow_abs, 0, &mut found)?;
        found.sort();

        let mut out = Vec::with_capacity(found.len());
        for artifact in found {
            let rel = artifact.strip_prefix(&patch).with_context(|| {
                format!("{} is not inside {}", artifact.display(), patch.display())
            })?;
            out.push((rel.to_path_buf(), artifact));
        }

        // Empty patch tree and stale artifacts both mean the same thing: there is
        // generated code for this crate, but this run cannot see it.
        if out.is_empty() {
            self.refuse_stale_artifacts()?;
        }
        Ok(out)
    }

    /// Refuse to build when generated code exists only under the old layout.
    ///
    /// Before the patch tree moved, artifacts lived at `.cargo-hole/src/`. Those
    /// files are still perfectly good generated code, and the naive thing -- walk
    /// only `patch/`, find nothing, build the crate as-is -- is the single worst
    /// outcome available here: `todo!()` has type `!`, so the crate compiles, the
    /// build succeeds, and the user gets a binary with every hole unimplemented
    /// and no indication that the generated code was skipped.
    ///
    /// Saying so is cheap, and the fix is one command.
    fn refuse_stale_artifacts(&self) -> Result<()> {
        let legacy = self.root.join(STORE_DIR).join("src");
        let mut stale = Vec::new();
        collect_artifacts(&legacy, Path::new(""), 0, &mut stale)?;
        if stale.is_empty() {
            return Ok(());
        }
        bail!(
            "found {} generated file(s) under {} from an older layout, which this \
             version no longer reads (artifacts now live in {}); refusing to build an \
             all-`todo!()` tree that would compile and look like a success. Run \
             `cargo hole fill` to regenerate them, or delete the old directory",
            stale.len(),
            legacy.display(),
            self.root.join(STORE_DIR).join(PATCH_DIR).display()
        )
    }

    /// Run `cargo build` in the shadow tree, forwarding `forwarded` verbatim.
    ///
    /// Output is inherited rather than captured: a build is long enough that the
    /// user wants to watch it, and pretending it is a quiet internal step would
    /// only mean buffering megabytes to print them at the end.
    ///
    /// No timeout is imposed. The probe's `--timeout` exists because a hung
    /// `cargo check` would otherwise wedge a fill run with nothing to show for
    /// it; a build the user asked for is a foreground command they can interrupt
    /// themselves.
    pub fn build(&self, options: &ProberOptions, forwarded: &[String]) -> Result<ExitStatus> {
        let mut cmd = options.cargo_command("build");
        cmd.args(forwarded);
        cmd.current_dir(&self.dir);
        cmd.status().with_context(|| {
            format!(
                "cannot run `{} build` in {}; is cargo on PATH?",
                options.cargo,
                self.dir.display()
            )
        })
    }

    /// Run the generated tree's binary, with the *crate's* directory as the
    /// working directory.
    ///
    /// `cargo run` gives the program the directory cargo was invoked in, so
    /// running it inside the build tree would hand the program the tree instead of
    /// the user's crate: a relative path the program opens (`./data/input.txt`,
    /// `include_str!` at runtime, a config beside the manifest) would resolve
    /// against a copy. The copy usually contains those files, which is what makes
    /// this quiet rather than loud -- it works until the program writes, or until
    /// the two diverge.
    ///
    /// So the working directory is deliberately *not* `self.dir`; cargo is pointed
    /// at the build tree's manifest instead. Output still lands in the tree's
    /// `target/`, which keeps the real `target/` untouched alongside the real
    /// source.
    pub fn run(&self, options: &ProberOptions, forwarded: &[String]) -> Result<ExitStatus> {
        let manifest = self.dir.join("Cargo.toml");
        let mut cmd = options.cargo_command("run");
        // Before `forwarded`, so a later `--manifest-path` from the user wins and
        // cargo reports its own error rather than silently running the wrong tree.
        cmd.arg("--manifest-path").arg(&manifest);
        cmd.args(forwarded);
        cmd.current_dir(&self.root);
        cmd.status().with_context(|| {
            format!(
                "cannot run `{} run` for {}; is cargo on PATH?",
                options.cargo,
                self.root.display()
            )
        })
    }
}

/// Make `path` absolute and lexically free of `.` and `..`, without touching the
/// filesystem.
///
/// `canonicalize` cannot be used for the guard because the shadow directory may
/// not exist yet. A lexical resolution is enough here: the guard only compares
/// one path against another, and both go through this same function, so they are
/// resolved consistently.
fn absolute(path: &Path) -> Result<PathBuf> {
    let joined = if path.is_absolute() {
        path.to_path_buf()
    } else {
        std::env::current_dir()
            .with_context(|| "cannot read the current directory to resolve a path")?
            .join(path)
    };

    let mut out = PathBuf::new();
    for component in joined.components() {
        match component {
            std::path::Component::CurDir => {}
            std::path::Component::ParentDir => {
                // Popping the root would silently turn `/..` into `/`, which is
                // the right answer, so a failed pop is not an error.
                out.pop();
            }
            other => out.push(other.as_os_str()),
        }
    }
    Ok(out)
}

/// Recursively mirror `src` into `dest`.
///
/// `shadow_abs` is the resolved shadow tree, skipped wherever it is met so that a
/// `--build-dir` placed inside the crate cannot make the copy recurse into
/// itself.
fn copy_tree(
    src: &Path,
    dest: &Path,
    rel_prefix: &Path,
    depth: usize,
    shadow_abs: &Path,
    overlaid: &std::collections::HashSet<PathBuf>,
    stats: &mut SyncStats,
) -> Result<()> {
    if depth > MAX_DEPTH {
        return Ok(());
    }
    let entries = match std::fs::read_dir(src) {
        Ok(e) => e,
        // An unreadable directory is skipped rather than fatal, matching how the
        // source walk treats one: a permission problem somewhere in the tree
        // should not stop the build of the rest.
        Err(_) => return Ok(()),
    };

    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name();
        let name_str = name.to_string_lossy();

        if SKIP_ANY_DEPTH.iter().any(|s| *s == name_str) {
            continue;
        }
        if path == shadow_abs {
            continue;
        }

        let Ok(file_type) = entry.file_type() else {
            continue;
        };
        let target = dest.join(&name);
        // Relative to the crate root, which is the form the artifact list uses.
        let rel = rel_prefix.join(&name);

        if file_type.is_dir() {
            std::fs::create_dir_all(&target)
                .with_context(|| format!("cannot create {}", target.display()))?;
            copy_tree(&path, &target, &rel, depth + 1, shadow_abs, overlaid, stats)?;
        } else if file_type.is_file() {
            // A source file that has an artifact is left to the overlay, which
            // runs next. Copying it here would write the original `todo!()` and
            // then immediately overwrite it, so the file would change twice on
            // every run and its mtime would never settle.
            if overlaid.contains(&rel) {
                continue;
            }
            copy_if_changed(&path, &target, stats)?;
        }
        // A symlinked directory is skipped: following it risks a cycle, and
        // following it inconsistently would be worse. Symlinked files are copied
        // by content, which `fs::read` does for us.
    }
    Ok(())
}

/// Every `.rs` file under `dir`, skipping the shadow tree and dot-directories.
///
/// Dot-directories are skipped because the store keeps its lock and its ledger
/// in plain files at the top level; anything hidden inside is not an artifact.
fn collect_artifacts(
    dir: &Path,
    shadow_abs: &Path,
    depth: usize,
    out: &mut Vec<PathBuf>,
) -> Result<()> {
    if depth > MAX_DEPTH {
        return Ok(());
    }
    let entries = match std::fs::read_dir(dir) {
        Ok(e) => e,
        Err(_) => return Ok(()),
    };

    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.starts_with('.') || path == shadow_abs {
            continue;
        }
        let Ok(file_type) = entry.file_type() else {
            continue;
        };
        if file_type.is_dir() {
            collect_artifacts(&path, shadow_abs, depth + 1, out)?;
        } else if path.extension().is_some_and(|e| e == "rs") {
            out.push(path);
        }
    }
    Ok(())
}

/// Overlay one artifact at `dest`, preferring a symlink to the artifact itself.
///
/// The link matters because rustc reports errors against paths *inside the build
/// tree* (`.../.cargo-hole/build/src/util.rs`). A copied artifact means the file
/// the user is told to open is a duplicate, and `sync` would quietly overwrite
/// their edit on the next run -- a fix that vanishes with no explanation. With a
/// link, both names are the same file, so editing the reported path is editing the
/// generated code, and cargo's mtime check sees the change.
///
/// Falls back to copying whenever a link cannot be made (a filesystem without
/// symlink support, or Windows without the privilege) and whenever `dest` already
/// exists as something other than the link we want. The fallback is not a
/// degraded mode to be avoided at all costs -- it just means edits must be made to
/// the patch tree instead.
fn overlay(artifact: &Path, dest: &Path, stats: &mut SyncStats) -> Result<()> {
    if let Some(parent) = dest.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("cannot create {}", parent.display()))?;
    }

    // Already the right link? Then this run has nothing to do, and the mtime must
    // stay put so cargo's incremental cache survives.
    if let Ok(existing) = std::fs::read_link(dest)
        && existing == artifact
    {
        stats.linked += 1;
        return Ok(());
    }

    // Remove whatever is there -- a stale link to a moved patch tree, or a copy
    // from an earlier run. `remove_file` on a symlink removes the link, not its
    // target, so the artifact is never harmed.
    match std::fs::remove_file(dest) {
        Ok(()) => {}
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => {
            return Err(e).with_context(|| format!("cannot replace {}", dest.display()));
        }
    }
    // `remove_file` does not remove a directory, and something that is now a
    // directory where a file belongs would make the link below fail confusingly.
    if dest.is_dir() {
        let _ = std::fs::remove_dir_all(dest);
    }

    match symlink_file(artifact, dest) {
        Ok(()) => {
            stats.linked += 1;
            Ok(())
        }
        // The fallback is deliberately silent. A user on a filesystem without
        // links gets a working build either way; warning on every run about a
        // property of their filesystem would be noise.
        Err(_) => copy_if_changed(artifact, dest, stats),
    }
}

/// Symlink a file, spelled for the host platform.
#[cfg(unix)]
fn symlink_file(target: &Path, link: &Path) -> std::io::Result<()> {
    std::os::unix::fs::symlink(target, link)
}

#[cfg(windows)]
fn symlink_file(target: &Path, link: &Path) -> std::io::Result<()> {
    std::os::windows::fs::symlink_file(target, link)
}

/// Write `src` to `dest` unless the bytes are already there.
///
/// Skipping identical content is what preserves mtimes, and therefore what keeps
/// cargo's incremental cache useful across runs. It also makes `sync` safe to
/// call repeatedly.
fn copy_if_changed(src: &Path, dest: &Path, stats: &mut SyncStats) -> Result<()> {
    let data = std::fs::read(src).with_context(|| format!("cannot read {}", src.display()))?;

    if std::fs::read(dest).is_ok_and(|existing| existing == data) {
        stats.reused += 1;
        return Ok(());
    }

    if let Some(parent) = dest.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("cannot create {}", parent.display()))?;
    }
    std::fs::write(dest, &data).with_context(|| format!("cannot write {}", dest.display()))?;
    stats.copied += 1;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU32, Ordering};

    const MANIFEST: &str = "Cargo.toml";

    /// A throwaway crate under `target/`, so nothing lands in `/tmp`.
    struct Fixture {
        dir: PathBuf,
    }

    impl Fixture {
        /// Build a crate whose `src/lib.rs` has a hole and whose `src/helper.rs`
        /// does not, then lay down an artifact for `lib.rs` only -- which is
        /// exactly the shape a real `fill` leaves behind.
        fn filled(tag: &str, answer: &str) -> Fixture {
            static NEXT: AtomicU32 = AtomicU32::new(0);
            let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("target/shadow-tests")
                .join(format!(
                    "{tag}-{}-{}",
                    std::process::id(),
                    NEXT.fetch_add(1, Ordering::Relaxed)
                ));
            let _ = std::fs::remove_dir_all(&dir);
            std::fs::create_dir_all(dir.join("src")).unwrap();
            std::fs::write(
                dir.join(MANIFEST),
                "[package]\nname = \"shadowtest\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[workspace]\n",
            )
            .unwrap();
            std::fs::write(
                dir.join("src/lib.rs"),
                "pub mod helper;\npub fn answer() -> i64 {\n    todo!(\"spec: return 42\")\n}\n",
            )
            .unwrap();
            std::fs::write(
                dir.join("src/helper.rs"),
                "pub fn plain() -> &'static str {\n    \"no hole here\"\n}\n",
            )
            .unwrap();

            // The artifact: what `fill` would have written for lib.rs.
            let artifact_dir = dir.join(STORE_DIR).join(PATCH_DIR).join("src");
            std::fs::create_dir_all(&artifact_dir).unwrap();
            std::fs::write(
                artifact_dir.join("lib.rs"),
                format!("pub mod helper;\npub fn answer() -> i64 {{\n    {answer}\n}}\n"),
            )
            .unwrap();

            Fixture { dir }
        }

        fn shadow(&self) -> Shadow {
            Shadow::new(self.dir.clone(), None).unwrap()
        }

        fn read(&self, rel: &str) -> String {
            std::fs::read_to_string(self.dir.join(rel)).unwrap()
        }

        /// Convenience for tests that only care about the built tree's bytes.
        fn shadow_read(&self, rel: &str) -> String {
            std::fs::read_to_string(self.dir.join(STORE_DIR).join(SHADOW_DIR_NAME).join(rel))
                .unwrap()
        }
    }

    #[test]
    fn the_shadow_gets_artifact_code_and_source_files_alike() {
        let fx = Fixture::filled("mix", "42");
        let shadow = fx.shadow();
        let stats = shadow.sync().unwrap();

        assert_eq!(stats.artifacts, 1, "one artifact was overlaid");
        // The hole is filled...
        let lib = fx.shadow_read("src/lib.rs");
        assert!(lib.contains("42"), "artifact code missing:\n{lib}");
        assert!(!lib.contains("todo!"), "the hole should be filled:\n{lib}");

        // ...and the hole-free file came across, or the crate would not compile.
        let helper = fx.shadow_read("src/helper.rs");
        assert!(helper.contains("no hole here"), "helper not mirrored");

        // The manifest has to come too, or cargo has nothing to build.
        assert!(
            shadow.dir().join(MANIFEST).exists(),
            "manifest not mirrored"
        );
        assert_eq!(stats.holes_left, 0, "nothing should still be todo!()");
    }

    #[test]
    fn syncing_does_not_touch_the_real_source() {
        let fx = Fixture::filled("untouched", "42");
        let before_lib = fx.read("src/lib.rs");
        let before_helper = fx.read("src/helper.rs");
        let before_artifact = fx.read(".cargo-hole/patch/src/lib.rs");

        fx.shadow().sync().unwrap();

        assert_eq!(fx.read("src/lib.rs"), before_lib, "source rewritten");
        assert_eq!(fx.read("src/helper.rs"), before_helper, "source rewritten");
        assert_eq!(
            fx.read(".cargo-hole/patch/src/lib.rs"),
            before_artifact,
            "artifact rewritten"
        );
    }

    #[test]
    fn the_shadow_tree_is_not_mistaken_for_an_artifact() {
        // The trap: the shadow lives *inside* the store, so a second sync that
        // enumerated the store naively would find its own output and overlay it
        // back on itself -- and the artifact count would grow with every run.
        let fx = Fixture::filled("recursive", "42");
        let shadow = fx.shadow();

        let first = shadow.sync().unwrap();
        let second = shadow.sync().unwrap();
        let third = shadow.sync().unwrap();

        assert_eq!(first.artifacts, 1, "{first:?}");
        assert_eq!(second.artifacts, 1, "the shadow was counted as an artifact");
        assert_eq!(third.artifacts, 1, "{third:?}");
    }

    #[test]
    fn a_second_sync_rewrites_nothing_so_the_incremental_cache_survives() {
        let fx = Fixture::filled("incremental", "42");
        let shadow = fx.shadow();

        let first = shadow.sync().unwrap();
        assert!(first.copied > 0, "the first sync copies: {first:?}");

        let second = shadow.sync().unwrap();
        assert_eq!(
            second.copied, 0,
            "a repeat sync must write nothing: {second:?}"
        );
        assert!(second.reused > 0, "{second:?}");
    }

    #[test]
    fn a_changed_artifact_replaces_the_old_one() {
        // The shadow must not become a cache of stale generated code.
        let fx = Fixture::filled("changed", "42");
        let shadow = fx.shadow();
        shadow.sync().unwrap();
        assert!(fx.shadow_read("src/lib.rs").contains("42"));

        // Regenerate the artifact with different code, as a later `fill` would.
        std::fs::write(
            fx.dir.join(STORE_DIR).join(PATCH_DIR).join("src/lib.rs"),
            "pub mod helper;\npub fn answer() -> i64 {\n    7 + 1\n}\n",
        )
        .unwrap();
        shadow.sync().unwrap();

        let lib = fx.shadow_read("src/lib.rs");
        assert!(
            lib.contains("7 + 1"),
            "the new artifact did not replace the old:\n{lib}"
        );
        assert!(!lib.contains("42"), "stale artifact code survived:\n{lib}");
    }

    #[test]
    fn an_unfilled_hole_is_counted_but_is_not_an_error() {
        // A hole left as `todo!()` still compiles, so it must not fail the sync;
        // but the build then proves less, so it must be reported.
        let fx = Fixture::filled("unfilled", "todo!(\"spec: return 42\")");
        let stats = fx.shadow().sync().unwrap();
        assert_eq!(stats.holes_left, 1, "{stats:?}");
        assert_eq!(stats.artifacts, 1, "{stats:?}");
    }

    #[test]
    fn build_output_and_dependencies_are_not_copied() {
        let fx = Fixture::filled("skip", "42");
        std::fs::create_dir_all(fx.dir.join("target")).unwrap();
        std::fs::write(fx.dir.join("target/big.bin"), vec![0u8; 4096]).unwrap();
        std::fs::create_dir_all(fx.dir.join("node_modules/pkg")).unwrap();
        std::fs::write(fx.dir.join("node_modules/pkg/index.js"), "x").unwrap();
        std::fs::create_dir_all(fx.dir.join(".git")).unwrap();
        std::fs::write(fx.dir.join(".git/HEAD"), "ref: refs/heads/main\n").unwrap();
        // A nested `target` (a workspace member's) must be skipped too.
        std::fs::create_dir_all(fx.dir.join("member/target")).unwrap();
        std::fs::write(fx.dir.join("member/target/junk.rs"), "junk").unwrap();

        let shadow = fx.shadow();
        shadow.sync().unwrap();

        assert!(!shadow.dir().join("target").exists(), "target copied");
        assert!(
            !shadow.dir().join("node_modules").exists(),
            "node_modules copied"
        );
        assert!(!shadow.dir().join(".git").exists(), ".git copied");
        assert!(
            !shadow.dir().join("member/target").exists(),
            "nested target copied"
        );
    }

    #[test]
    fn a_cargo_config_directory_is_copied_because_it_changes_the_build() {
        // Skipping dot-entries wholesale would be simpler, and would silently
        // build something other than the user's crate when they configure cargo
        // through `.cargo/config.toml`.
        let fx = Fixture::filled("cargoconfig", "42");
        std::fs::create_dir_all(fx.dir.join(".cargo")).unwrap();
        std::fs::write(
            fx.dir.join(".cargo/config.toml"),
            "[build]\nrustflags = [\"--cfg\", \"custom\"]\n",
        )
        .unwrap();

        let shadow = fx.shadow();
        shadow.sync().unwrap();

        let copied = fx.shadow_read(".cargo/config.toml");
        assert!(
            copied.contains("rustflags"),
            "cargo config not copied: {copied}"
        );
    }

    #[test]
    fn clean_removes_the_shadow_but_not_the_source() {
        let fx = Fixture::filled("clean", "42");
        let shadow = fx.shadow();
        shadow.sync().unwrap();
        assert!(shadow.dir().exists());

        shadow.clean().unwrap();

        assert!(!shadow.dir().exists(), "shadow survived clean");
        assert!(fx.dir.join("src/lib.rs").exists(), "clean took the source");
        assert!(fx.dir.join(MANIFEST).exists(), "clean took the manifest");
        assert!(
            fx.dir
                .join(STORE_DIR)
                .join(PATCH_DIR)
                .join("src/lib.rs")
                .exists(),
            "clean took the artifact"
        );
    }

    #[test]
    fn clean_on_a_missing_shadow_is_fine() {
        let fx = Fixture::filled("clean-missing", "42");
        let shadow = fx.shadow();
        // Never synced: nothing to remove, and asking anyway must not fail.
        shadow.clean().unwrap();
        shadow.clean().unwrap();
    }

    #[test]
    fn a_shadow_that_is_the_root_is_refused() {
        // `clean` deletes the shadow, so this would delete the crate.
        let fx = Fixture::filled("root-shadow", "42");
        let err = Shadow::new(fx.dir.clone(), Some(fx.dir.clone())).unwrap_err();
        assert!(
            err.to_string().contains("cannot be the crate root"),
            "{err}"
        );
    }

    #[test]
    fn a_shadow_containing_the_root_is_refused() {
        // `clean` here would delete the whole checkout.
        let fx = Fixture::filled("ancestor-shadow", "42");
        let parent = fx.dir.parent().unwrap().to_path_buf();
        let err = Shadow::new(fx.dir.clone(), Some(parent)).unwrap_err();
        assert!(err.to_string().contains("contains the crate root"), "{err}");
    }

    #[test]
    fn a_relative_build_dir_that_escapes_the_crate_is_refused() {
        // The dangerous shape: `--build-dir` reached through `..`, which a raw
        // path comparison does not recognise as an ancestor. `clean` on this
        // would delete the crate's parent directory.
        let fx = Fixture::filled("dotdot", "42");
        let escaping = fx.dir.join("..");
        let err = Shadow::new(fx.dir.clone(), Some(escaping)).unwrap_err();
        assert!(err.to_string().contains("contains the crate root"), "{err}");

        // And the same via an explicitly relative path, which is how a user would
        // actually type it.
        let cwd = std::env::current_dir().unwrap();
        let rel = pathdiff(&fx.dir, &cwd).unwrap();
        let err = Shadow::new(
            pathdiff(&fx.dir, Path::new(".")).unwrap(),
            Some(rel.join("..")),
        )
        .unwrap_err();
        assert!(err.to_string().contains("contains the crate root"), "{err}");
    }

    /// `path` expressed relative to `base`, for building a relative `..` path in
    /// a test without hardcoding a depth.
    fn pathdiff(path: &Path, base: &Path) -> Option<PathBuf> {
        let path = absolute(path).ok()?;
        let base = absolute(base).ok()?;
        let mut a = path.components().peekable();
        let mut b = base.components().peekable();
        while a.peek().is_some() && a.peek() == b.peek() {
            a.next();
            b.next();
        }
        let mut out = PathBuf::new();
        for _ in b {
            out.push("..");
        }
        for c in a {
            out.push(c.as_os_str());
        }
        Some(out)
    }

    #[test]
    fn clean_never_deletes_an_ancestor_even_if_the_tree_exists() {
        // The guard has to hold at delete time too, not only at construction.
        let fx = Fixture::filled("clean-ancestor", "42");
        let parent = fx.dir.parent().unwrap().to_path_buf();
        // Construction refuses it, so the destructive path cannot be reached.
        assert!(Shadow::new(fx.dir.clone(), Some(parent.clone())).is_err());
        assert!(fx.dir.exists(), "the crate must still be there");
        assert!(parent.exists(), "the parent must still be there");
    }

    #[test]
    fn absolute_resolves_dot_and_dotdot_without_the_filesystem() {
        let base = if cfg!(windows) { "C:\\a\\b" } else { "/a/b" };
        let base = Path::new(base);
        assert_eq!(absolute(&base.join("x/../y")).unwrap(), base.join("y"));
        assert_eq!(absolute(&base.join("./x")).unwrap(), base.join("x"));
        assert_eq!(
            absolute(&base.join("a/b/../..")).unwrap(),
            base.to_path_buf()
        );
        // A relative path is anchored at the current directory.
        assert!(absolute(Path::new("rel")).unwrap().is_absolute());
    }

    #[test]
    fn a_custom_build_dir_inside_the_crate_does_not_recurse() {
        // A `--build-dir` inside the crate is legal; the copy must not walk into
        // its own output.
        let fx = Fixture::filled("custom", "42");
        let shadow = Shadow::new(fx.dir.clone(), Some(fx.dir.join("shadow-here"))).unwrap();
        let stats = shadow.sync().unwrap();

        assert_eq!(stats.artifacts, 1, "{stats:?}");
        assert!(shadow.dir().join("src/lib.rs").exists());
        // Nothing nested a copy of itself.
        assert!(
            !shadow.dir().join("shadow-here").exists(),
            "recursed into itself"
        );
        // And it is not inside the store, so it is not an artifact source.
        assert!(!fx.dir.join(STORE_DIR).join("shadow-here").exists());
    }

    /// The overlay is a symlink, so the file rustc names in an error message is
    /// the generated code itself rather than a duplicate that `sync` will revert.
    #[test]
    #[cfg(unix)]
    fn an_overlaid_artifact_is_the_same_file_as_the_generated_code() {
        let fx = Fixture::filled("link-identity", "42");
        let shadow = fx.shadow();
        let stats = shadow.sync().unwrap();

        assert_eq!(stats.artifacts, 1, "{stats:?}");
        assert_eq!(stats.linked, 1, "the artifact should be linked: {stats:?}");

        let built = fx
            .dir
            .join(STORE_DIR)
            .join(SHADOW_DIR_NAME)
            .join("src/lib.rs");
        let generated = fx.dir.join(STORE_DIR).join(PATCH_DIR).join("src/lib.rs");
        assert!(
            std::fs::symlink_metadata(&built).unwrap().is_symlink(),
            "the artifact was copied instead of linked"
        );

        // Edit the path rustc would report. It must land in the generated code.
        let edited = "pub mod helper;\npub fn answer() -> i64 {\n    7\n}\n";
        std::fs::write(&built, edited).unwrap();
        assert_eq!(
            std::fs::read_to_string(&generated).unwrap(),
            edited,
            "editing the build tree did not reach the generated code, so the fix \
             would be silently reverted by the next build"
        );
    }

    /// A second sync must leave the link alone, or the artifact's mtime would move
    /// on every run and cargo's incremental cache would never apply.
    #[test]
    #[cfg(unix)]
    fn a_second_sync_leaves_the_link_in_place() {
        let fx = Fixture::filled("link-stable", "42");
        let shadow = fx.shadow();
        shadow.sync().unwrap();
        let built = fx
            .dir
            .join(STORE_DIR)
            .join(SHADOW_DIR_NAME)
            .join("src/lib.rs");
        let first = std::fs::symlink_metadata(&built).unwrap();

        let second = shadow.sync().unwrap();

        assert_eq!(second.linked, 1, "{second:?}");
        assert_eq!(second.copied, 0, "nothing should be rewritten: {second:?}");
        assert!(
            std::fs::symlink_metadata(&built).unwrap().is_symlink(),
            "the second sync replaced the link"
        );
        // The link's own mtime is what a rebuild would move; it must be untouched.
        assert_eq!(
            first.modified().unwrap(),
            std::fs::symlink_metadata(&built)
                .unwrap()
                .modified()
                .unwrap(),
            "the link was rewritten, so its mtime moved and the incremental cache \
             would be invalidated on every run"
        );
    }

    /// Old artifacts at `.cargo-hole/src/` must not be silently ignored: the crate
    /// would compile anyway, because `todo!()` has type `!`, and the user would get
    /// a "successful" build with every hole unimplemented.
    #[test]
    fn stale_artifacts_from_the_old_layout_are_refused() {
        let fx = Fixture::filled("stale", "42");
        let patch = fx.dir.join(STORE_DIR).join(PATCH_DIR);
        let legacy = fx.dir.join(STORE_DIR).join("src");
        std::fs::create_dir_all(&legacy).unwrap();
        for entry in std::fs::read_dir(patch.join("src")).unwrap().flatten() {
            std::fs::rename(entry.path(), legacy.join(entry.file_name())).unwrap();
        }
        std::fs::remove_dir_all(&patch).unwrap();

        let err = fx.shadow().sync().unwrap_err().to_string();
        assert!(
            err.contains("older layout"),
            "the refusal should explain itself: {err}"
        );
        assert!(
            err.contains("cargo hole fill"),
            "the refusal should say what to do: {err}"
        );
    }

    /// The open-hole count must survive the symlink overlay.
    ///
    /// `util::walk` reads `DirEntry::file_type`, which describes the *link* rather
    /// than its target. When artifacts became symlinks, a naive walk stopped seeing
    /// the files that still contain holes, `holes_left` read zero, and the "holes
    /// are still open" warning silently disappeared -- making an all-`todo!()`
    /// build look like a clean success, which is the one thing that warning exists
    /// to prevent.
    #[test]
    #[cfg(unix)]
    fn open_holes_are_still_counted_through_a_symlinked_artifact() {
        let fx = Fixture::filled("link-holes", "42");
        // An artifact that still holds a hole, as a partial fill would leave.
        std::fs::write(
            fx.dir.join(STORE_DIR).join(PATCH_DIR).join("src/lib.rs"),
            "pub mod helper;\npub fn answer() -> i64 {\n    todo!(\"spec: still open\")\n}\n",
        )
        .unwrap();

        let shadow = fx.shadow();
        let stats = shadow.sync().unwrap();

        assert_eq!(stats.linked, 1, "{stats:?}");
        assert_eq!(
            stats.holes_left, 1,
            "the hole behind the symlink went uncounted: {stats:?}"
        );
    }

    #[test]
    fn a_crate_without_artifacts_still_syncs() {
        // `list` and a never-filled crate are legitimate: there is nothing to
        // overlay, and the build is then just a build of the crate.
        let fx = Fixture::filled("no-artifacts", "42");
        std::fs::remove_dir_all(fx.dir.join(STORE_DIR)).unwrap();

        let shadow = fx.shadow();
        let stats = shadow.sync().unwrap();

        assert_eq!(stats.artifacts, 0, "{stats:?}");
        assert!(!stats.overlaid_anything());
        // The source came across as-is, hole and all.
        let lib = fx.shadow_read("src/lib.rs");
        assert!(lib.contains("todo!"), "source not mirrored:\n{lib}");
        assert_eq!(stats.holes_left, 1, "{stats:?}");
    }

    #[test]
    fn nested_source_directories_are_mirrored() {
        let fx = Fixture::filled("nested", "42");
        std::fs::create_dir_all(fx.dir.join("src/deep/deeper")).unwrap();
        std::fs::write(fx.dir.join("src/deep/deeper/mod.rs"), "pub fn d() {}\n").unwrap();

        let shadow = fx.shadow();
        shadow.sync().unwrap();

        assert!(shadow.dir().join("src/deep/deeper/mod.rs").exists());
    }

    #[test]
    fn a_data_file_read_by_include_str_is_mirrored() {
        // `include_str!` is resolved relative to the source file, so a crate that
        // reads a data file would fail to build in a shadow that copied only
        // `.rs` files.
        let fx = Fixture::filled("data", "42");
        std::fs::write(fx.dir.join("src/data.txt"), "hello\n").unwrap();
        std::fs::write(fx.dir.join("build.rs"), "fn main() {}\n").unwrap();

        let shadow = fx.shadow();
        shadow.sync().unwrap();

        assert_eq!(fx.shadow_read("src/data.txt"), "hello\n");
        assert!(
            shadow.dir().join("build.rs").exists(),
            "build script not mirrored"
        );
    }

    #[test]
    fn stats_report_a_useful_summary() {
        let fx = Fixture::filled("stats", "42");
        let stats = fx.shadow().sync().unwrap();
        assert!(stats.overlaid_anything());
        assert_eq!(stats.holes_left, 0);
        // The manifest and the hole-free helper come across as copies; the
        // artifact for lib.rs is linked rather than copied, so it is counted
        // separately.
        assert_eq!(stats.linked, 1, "{stats:?}");
        assert!(stats.copied >= 2, "manifest and helper.rs: {stats:?}");
    }
}
